
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.graph.backend;

import java.awt.Color;
import java_cup.runtime.*;
import org.graph.backend.tree.Node;
import org.graph.frontend.canvas.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class GraphParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public GraphParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public GraphParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public GraphParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\045\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\003\004\000\002\003\004" +
    "\000\002\004\004\000\002\004\004\000\002\004\004\000" +
    "\002\004\004\000\002\004\004\000\002\005\015\000\002" +
    "\013\003\000\002\013\003\000\002\006\015\000\002\007" +
    "\017\000\002\010\021\000\002\011\015\000\002\012\017" +
    "\000\002\015\005\000\002\015\005\000\002\015\003\000" +
    "\002\016\005\000\002\016\005\000\002\016\003\000\002" +
    "\016\004\000\002\017\003\000\002\017\005\000\002\014" +
    "\003\000\002\014\003\000\002\014\003\000\002\014\003" +
    "\000\002\014\003\000\002\014\003\000\002\014\003\000" +
    "\002\014\003\000\002\014\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\171\000\010\003\006\015\004\016\005\001\002\000" +
    "\014\017\054\020\056\021\051\022\055\023\053\001\002" +
    "\000\004\036\015\001\002\000\010\003\006\015\004\016" +
    "\005\001\002\000\012\002\uffff\003\uffff\015\uffff\016\uffff" +
    "\001\002\000\012\002\012\003\006\015\004\016\005\001" +
    "\002\000\012\002\000\003\000\015\000\016\000\001\002" +
    "\000\004\002\001\001\002\000\012\002\ufffc\003\ufffc\015" +
    "\ufffc\016\ufffc\001\002\000\012\002\ufffd\003\ufffd\015\ufffd" +
    "\016\ufffd\001\002\000\004\037\016\001\002\000\004\012" +
    "\017\001\002\000\006\022\022\035\020\001\002\000\004" +
    "\014\ufff4\001\002\000\004\014\023\001\002\000\004\014" +
    "\ufff5\001\002\000\006\004\027\012\024\001\002\000\006" +
    "\004\027\012\024\001\002\000\016\006\uffec\007\uffec\010" +
    "\035\011\036\013\uffec\014\uffec\001\002\000\022\004\027" +
    "\006\uffe9\007\uffe9\010\uffe9\011\uffe9\012\024\013\uffe9\014" +
    "\uffe9\001\002\000\022\004\uffe7\006\uffe7\007\uffe7\010\uffe7" +
    "\011\uffe7\012\uffe7\013\uffe7\014\uffe7\001\002\000\010\006" +
    "\033\007\032\014\031\001\002\000\006\004\027\012\024" +
    "\001\002\000\006\004\027\012\024\001\002\000\006\004" +
    "\027\012\024\001\002\000\016\006\uffee\007\uffee\010\035" +
    "\011\036\013\uffee\014\uffee\001\002\000\006\004\027\012" +
    "\024\001\002\000\006\004\027\012\024\001\002\000\016" +
    "\006\uffea\007\uffea\010\uffea\011\uffea\013\uffea\014\uffea\001" +
    "\002\000\016\006\uffeb\007\uffeb\010\uffeb\011\uffeb\013\uffeb" +
    "\014\uffeb\001\002\000\016\006\uffed\007\uffed\010\035\011" +
    "\036\013\uffed\014\uffed\001\002\000\010\006\033\007\032" +
    "\014\043\001\002\000\006\004\027\012\024\001\002\000" +
    "\010\006\033\007\032\013\045\001\002\000\012\002\ufff6" +
    "\003\ufff6\015\ufff6\016\ufff6\001\002\000\016\006\uffe8\007" +
    "\uffe8\010\uffe8\011\uffe8\013\uffe8\014\uffe8\001\002\000\010" +
    "\006\033\007\032\013\050\001\002\000\022\004\uffe6\006" +
    "\uffe6\007\uffe6\010\uffe6\011\uffe6\012\uffe6\013\uffe6\014\uffe6" +
    "\001\002\000\004\012\156\001\002\000\012\002\ufffe\003" +
    "\ufffe\015\ufffe\016\ufffe\001\002\000\004\012\136\001\002" +
    "\000\004\012\122\001\002\000\004\012\105\001\002\000" +
    "\004\012\057\001\002\000\004\005\061\001\002\000\012" +
    "\002\ufffa\003\ufffa\015\ufffa\016\ufffa\001\002\000\004\014" +
    "\062\001\002\000\006\004\027\012\024\001\002\000\010" +
    "\006\033\007\032\014\064\001\002\000\006\004\027\012" +
    "\024\001\002\000\010\006\033\007\032\014\066\001\002" +
    "\000\006\004\027\012\024\001\002\000\010\006\033\007" +
    "\032\014\070\001\002\000\024\024\102\025\074\026\073" +
    "\027\100\030\076\031\077\032\101\033\071\034\075\001" +
    "\002\000\004\013\uffde\001\002\000\004\013\103\001\002" +
    "\000\004\013\uffe3\001\002\000\004\013\uffe4\001\002\000" +
    "\004\013\uffdd\001\002\000\004\013\uffe1\001\002\000\004" +
    "\013\uffe0\001\002\000\004\013\uffe2\001\002\000\004\013" +
    "\uffdf\001\002\000\004\013\uffe5\001\002\000\012\002\ufff0" +
    "\003\ufff0\015\ufff0\016\ufff0\001\002\000\012\002\ufff8\003" +
    "\ufff8\015\ufff8\016\ufff8\001\002\000\004\005\106\001\002" +
    "\000\004\014\107\001\002\000\006\004\027\012\024\001" +
    "\002\000\010\006\033\007\032\014\111\001\002\000\006" +
    "\004\027\012\024\001\002\000\010\006\033\007\032\014" +
    "\113\001\002\000\006\004\027\012\024\001\002\000\010" +
    "\006\033\007\032\014\115\001\002\000\006\004\027\012" +
    "\024\001\002\000\010\006\033\007\032\014\117\001\002" +
    "\000\024\024\102\025\074\026\073\027\100\030\076\031" +
    "\077\032\101\033\071\034\075\001\002\000\004\013\121" +
    "\001\002\000\012\002\ufff2\003\ufff2\015\ufff2\016\ufff2\001" +
    "\002\000\004\005\124\001\002\000\012\002\ufffb\003\ufffb" +
    "\015\ufffb\016\ufffb\001\002\000\004\014\125\001\002\000" +
    "\006\004\027\012\024\001\002\000\010\006\033\007\032" +
    "\014\127\001\002\000\006\004\027\012\024\001\002\000" +
    "\010\006\033\007\032\014\131\001\002\000\006\004\027" +
    "\012\024\001\002\000\010\006\033\007\032\014\133\001" +
    "\002\000\024\024\102\025\074\026\073\027\100\030\076" +
    "\031\077\032\101\033\071\034\075\001\002\000\004\013" +
    "\135\001\002\000\012\002\ufff3\003\ufff3\015\ufff3\016\ufff3" +
    "\001\002\000\004\005\140\001\002\000\012\002\ufff7\003" +
    "\ufff7\015\ufff7\016\ufff7\001\002\000\004\014\141\001\002" +
    "\000\006\004\027\012\024\001\002\000\010\006\033\007" +
    "\032\014\143\001\002\000\006\004\027\012\024\001\002" +
    "\000\010\006\033\007\032\014\145\001\002\000\006\004" +
    "\027\012\024\001\002\000\010\006\033\007\032\014\147" +
    "\001\002\000\006\004\027\012\024\001\002\000\010\006" +
    "\033\007\032\014\151\001\002\000\006\004\027\012\024" +
    "\001\002\000\010\006\033\007\032\014\153\001\002\000" +
    "\024\024\102\025\074\026\073\027\100\030\076\031\077" +
    "\032\101\033\071\034\075\001\002\000\004\013\155\001" +
    "\002\000\012\002\ufff1\003\ufff1\015\ufff1\016\ufff1\001\002" +
    "\000\004\005\160\001\002\000\012\002\ufff9\003\ufff9\015" +
    "\ufff9\016\ufff9\001\002\000\004\014\161\001\002\000\006" +
    "\004\027\012\024\001\002\000\010\006\033\007\032\014" +
    "\163\001\002\000\006\004\027\012\024\001\002\000\010" +
    "\006\033\007\032\014\165\001\002\000\006\004\027\012" +
    "\024\001\002\000\010\006\033\007\032\014\167\001\002" +
    "\000\006\004\027\012\024\001\002\000\010\006\033\007" +
    "\032\014\171\001\002\000\024\024\102\025\074\026\073" +
    "\027\100\030\076\031\077\032\101\033\071\034\075\001" +
    "\002\000\004\013\173\001\002\000\012\002\uffef\003\uffef" +
    "\015\uffef\016\uffef\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\171\000\006\002\007\003\006\001\001\000\004\004" +
    "\051\001\001\000\004\005\013\001\001\000\004\003\012" +
    "\001\001\000\002\001\001\000\004\003\010\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\013" +
    "\020\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\015\027\016\024\017\025\001\001\000" +
    "\010\015\046\016\024\017\025\001\001\000\002\001\001" +
    "\000\004\017\045\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\015\041\016\024\017\025\001\001\000\006" +
    "\016\040\017\025\001\001\000\006\016\033\017\025\001" +
    "\001\000\002\001\001\000\004\017\037\001\001\000\004" +
    "\017\036\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\015\043\016\024" +
    "\017\025\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\156\001\001\000\002\001\001\000\004\010\136\001" +
    "\001\000\004\006\122\001\001\000\004\007\103\001\001" +
    "\000\004\011\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\015\062\016\024\017\025" +
    "\001\001\000\002\001\001\000\010\015\064\016\024\017" +
    "\025\001\001\000\002\001\001\000\010\015\066\016\024" +
    "\017\025\001\001\000\002\001\001\000\004\014\071\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\015\107\016\024\017\025" +
    "\001\001\000\002\001\001\000\010\015\111\016\024\017" +
    "\025\001\001\000\002\001\001\000\010\015\113\016\024" +
    "\017\025\001\001\000\002\001\001\000\010\015\115\016" +
    "\024\017\025\001\001\000\002\001\001\000\004\014\117" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\015\125" +
    "\016\024\017\025\001\001\000\002\001\001\000\010\015" +
    "\127\016\024\017\025\001\001\000\002\001\001\000\010" +
    "\015\131\016\024\017\025\001\001\000\002\001\001\000" +
    "\004\014\133\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\015\141\016\024\017\025\001\001\000\002\001\001" +
    "\000\010\015\143\016\024\017\025\001\001\000\002\001" +
    "\001\000\010\015\145\016\024\017\025\001\001\000\002" +
    "\001\001\000\010\015\147\016\024\017\025\001\001\000" +
    "\002\001\001\000\010\015\151\016\024\017\025\001\001" +
    "\000\002\001\001\000\004\014\153\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\015\161\016\024\017\025\001" +
    "\001\000\002\001\001\000\010\015\163\016\024\017\025" +
    "\001\001\000\002\001\001\000\010\015\165\016\024\017" +
    "\025\001\001\000\002\001\001\000\010\015\167\016\024" +
    "\017\025\001\001\000\002\001\001\000\004\014\171\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$GraphParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$GraphParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$GraphParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private GraphCanvas canvas;

    public GraphParser(GraphLexer lex, GraphCanvas canvas) {
        super(lex);
        this.canvas = canvas;
    }

    public void syntax_error(Symbol s) {
        System.out.println("Syntax error in line: " + (s.left) +
        " column: "+s.right+ ". didn't expect component: " +s.value+".");
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.out.println("Sintax error unrecovered in line: " +
        (s.left)+ " column: "+s.right+". Component: " + s.value + " not recognized.");
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$GraphParser$actions {
  private final GraphParser parser;

  /** Constructor */
  CUP$GraphParser$actions(GraphParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$GraphParser$do_action_part00000000(
    int                        CUP$GraphParser$act_num,
    java_cup.runtime.lr_parser CUP$GraphParser$parser,
    java.util.Stack            CUP$GraphParser$stack,
    int                        CUP$GraphParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$GraphParser$result;

      /* select the action based on the action number */
      switch (CUP$GraphParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= s EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).value;
		RESULT = start_val;
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$GraphParser$parser.done_parsing();
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // s ::= s s1 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // s ::= s1 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // s1 ::= GRAFICAR s2 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s1",1, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // s1 ::= ANIMAR s3 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s1",1, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // s1 ::= error s1 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s1",1, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // s2 ::= CIRCULO s4 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s2",2, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // s2 ::= CUADRADO s7 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s2",2, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // s2 ::= RECTANGULO s8 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s2",2, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // s2 ::= LINEA s5 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s2",2, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // s2 ::= POLIGONO s6 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s2",2, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // s3 ::= OBJETO ANTERIOR PARENTHESES_START anmt COMMA expr COMMA expr COMMA expr PARENTHESES_END 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s3",3, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-10)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // anmt ::= LINEA 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("anmt",9, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // anmt ::= CURVA 
            {
              Object RESULT =null;

              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("anmt",9, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // s4 ::= PARENTHESES_START NAME COMMA expr COMMA expr COMMA expr COMMA color PARENTHESES_END 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).right;
		Node x = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).right;
		Node y = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).right;
		Node r = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).value;
		
        String name = n;
        double xValue = x.getValue();
        double yValue = y.getValue();
        double rValue = r.getValue();
        Color colorValue = (Color) c;

        canvas.addCircle(name, xValue, yValue, rValue, colorValue);
    
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s4",4, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-10)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // s5 ::= PARENTHESES_START NAME COMMA expr COMMA expr COMMA expr COMMA expr COMMA color PARENTHESES_END 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-11)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-11)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-11)).value;
		int x1left = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).left;
		int x1right = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).right;
		Node x1 = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).value;
		int y1left = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).left;
		int y1right = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).right;
		Node y1 = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).value;
		int x2left = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).left;
		int x2right = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).right;
		Node x2 = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).value;
		int y2left = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).left;
		int y2right = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).right;
		Node y2 = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).value;
		
        String name = n;
        double x1Value = x1.getValue();
        double y1Value = y1.getValue();
        double x2Value = x2.getValue();
        double y2Value = y2.getValue();
        Color colorValue = (Color) c;

        canvas.addLine(name, x1Value, y1Value, x2Value, y2Value, colorValue);
    
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s5",5, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-12)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // s6 ::= PARENTHESES_START NAME COMMA expr COMMA expr COMMA expr COMMA expr COMMA expr COMMA color PARENTHESES_END 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-13)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-13)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-13)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-11)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-11)).right;
		Node x = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-11)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).right;
		Node y = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).value;
		int clleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).left;
		int clright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).right;
		Node cl = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).value;
		int wleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).right;
		Node w = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).right;
		Node h = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).value;
		
        String name = n;
        double xValue = x.getValue();
        double yValue = y.getValue();
        int clValue = (int) cl.getValue();
        double wValue = w.getValue();
        double hValue = h.getValue();
        Color colorValue = (Color) c;

        canvas.addPol(name, xValue, yValue, clValue, wValue, hValue, colorValue);

    
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s6",6, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-14)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // s7 ::= PARENTHESES_START NAME COMMA expr COMMA expr COMMA expr COMMA color PARENTHESES_END 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).right;
		Node x = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).right;
		Node y = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).right;
		Node l = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).value;
		
        String name = n;
        double xValue = x.getValue();
        double yValue = y.getValue();
        double lValue = l.getValue();
        Color colorValue = (Color) c;

        canvas.addSqr(name, xValue, yValue, lValue, colorValue);
    
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s7",7, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-10)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // s8 ::= PARENTHESES_START NAME COMMA expr COMMA expr COMMA expr COMMA expr COMMA color PARENTHESES_END 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-11)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-11)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-11)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).right;
		Node x = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-9)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).right;
		Node y = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-7)).value;
		int l1left = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).left;
		int l1right = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).right;
		Node l1 = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-5)).value;
		int l2left = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).left;
		int l2right = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).right;
		Node l2 = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).value;
		
        String name = n;
        double xValue = x.getValue();
        double yValue = y.getValue();
        double l1Value = l1.getValue();
        double l2Value = l2.getValue();
        Color colorValue = (Color) c;

        canvas.addRec(name, xValue, yValue, l1Value, l2Value, colorValue);
    
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("s8",8, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-12)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expr ::= expr ADDITION term 
            {
              Node RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).right;
		Node e = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).right;
		Node t = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.peek()).value;
		 RESULT = new Node(e, t, Node.Type.ADDITION);
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr ::= expr SUBSTRACTION term 
            {
              Node RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).right;
		Node e = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).right;
		Node t = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.peek()).value;
		 RESULT = new Node(e, t, Node.Type.SUBSTRACTION); 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= term 
            {
              Node RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).right;
		Node t = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.peek()).value;
		 RESULT = t; 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // term ::= term MULTIPLICATION factor 
            {
              Node RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).right;
		Node t = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).right;
		Node f = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.peek()).value;
		 RESULT = new Node(t, f, Node.Type.MULTIPLICATION);
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("term",12, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // term ::= term DIVISION factor 
            {
              Node RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).right;
		Node t = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).right;
		Node f = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.peek()).value;
		 RESULT = new Node(t, f, Node.Type.DIVISION);
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("term",12, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // term ::= factor 
            {
              Node RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).right;
		Node f = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.peek()).value;
		 RESULT = f; 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("term",12, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // term ::= factor factor 
            {
              Node RESULT =null;
		int f1left = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).left;
		int f1right = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).right;
		Node f1 = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).value;
		int f2left = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).left;
		int f2right = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).right;
		Node f2 = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.peek()).value;
		 RESULT = new Node(f1, f2, Node.Type.MULTIPLICATION); 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("term",12, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // factor ::= NUMBER 
            {
              Node RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$GraphParser$stack.peek()).value;
		 RESULT = new Node(Double.parseDouble(n)); 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("factor",13, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // factor ::= PARENTHESES_START expr PARENTHESES_END 
            {
              Node RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).right;
		Node e = (Node)((java_cup.runtime.Symbol) CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-1)).value;
		 RESULT = e; 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("factor",13, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.elementAt(CUP$GraphParser$top-2)), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // color ::= AZUL 
            {
              Object RESULT =null;
		 RESULT = Color.BLUE; 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // color ::= ROJO 
            {
              Object RESULT =null;
		 RESULT = Color.RED; 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // color ::= AMARILLO 
            {
              Object RESULT =null;
		 RESULT = Color.YELLOW; 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // color ::= VERDE 
            {
              Object RESULT =null;
		 RESULT = Color.GREEN; 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // color ::= CELESTE 
            {
              Object RESULT =null;
		 RESULT = Color.CYAN; 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // color ::= NEGRO 
            {
              Object RESULT =null;
		 RESULT = Color.BLACK; 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // color ::= ROSADO 
            {
              Object RESULT =null;
		 RESULT = Color.PINK; 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // color ::= CAFE 
            {
              Object RESULT =null;
		 RESULT = new Color(139, 69, 19); 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // color ::= NARANJA 
            {
              Object RESULT =null;
		 RESULT = Color.ORANGE; 
              CUP$GraphParser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GraphParser$stack.peek()), RESULT);
            }
          return CUP$GraphParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$GraphParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$GraphParser$do_action(
    int                        CUP$GraphParser$act_num,
    java_cup.runtime.lr_parser CUP$GraphParser$parser,
    java.util.Stack            CUP$GraphParser$stack,
    int                        CUP$GraphParser$top)
    throws java.lang.Exception
    {
              return CUP$GraphParser$do_action_part00000000(
                               CUP$GraphParser$act_num,
                               CUP$GraphParser$parser,
                               CUP$GraphParser$stack,
                               CUP$GraphParser$top);
    }
}

}
