
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.graph.backend;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 16;
  public static final int PARENTHESES_END = 9;
  public static final int DIVISION = 7;
  public static final int CURVA = 27;
  public static final int ANIMAR = 12;
  public static final int CAFE = 25;
  public static final int NAME = 3;
  public static final int CUADRADO = 14;
  public static final int OBJETO = 28;
  public static final int VERDE = 21;
  public static final int PARENTHESES_START = 8;
  public static final int ROJO = 19;
  public static final int ROSADO = 24;
  public static final int GRAFICAR = 11;
  public static final int AMARILLO = 20;
  public static final int COMMA = 10;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int MULTIPLICATION = 6;
  public static final int CELESTE = 22;
  public static final int POLIGONO = 17;
  public static final int error = 1;
  public static final int SUBSTRACTION = 5;
  public static final int CIRCULO = 13;
  public static final int AZUL = 18;
  public static final int ANTERIOR = 29;
  public static final int NEGRO = 23;
  public static final int ADDITION = 4;
  public static final int NARANJA = 26;
  public static final int RECTANGULO = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "NAME",
  "ADDITION",
  "SUBSTRACTION",
  "MULTIPLICATION",
  "DIVISION",
  "PARENTHESES_START",
  "PARENTHESES_END",
  "COMMA",
  "GRAFICAR",
  "ANIMAR",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "LINEA",
  "POLIGONO",
  "AZUL",
  "ROJO",
  "AMARILLO",
  "VERDE",
  "CELESTE",
  "NEGRO",
  "ROSADO",
  "CAFE",
  "NARANJA",
  "CURVA",
  "OBJETO",
  "ANTERIOR"
  };
}

